xpumd/level-zero-go: small fix to examples dockerfile
Error out if curl fails. Use strict mode for sha256sum.

Signed-off-by: Markus Lehtonen <markus.lehtonen@intel.com>

Dev-SHA: 4d082967db9d255670e941b246811bb6aefe7ef1

diff --git a/xpumd/level-zero-go/examples/Dockerfile b/xpumd/level-zero-go/examples/Dockerfile
--- a/xpumd/level-zero-go/examples/Dockerfile
+++ b/xpumd/level-zero-go/examples/Dockerfile
@@ -38,14 +38,14 @@ RUN IGC_CORE_RELEASE=${IGC_CORE_VERSION%%+*} && \
 
 RUN curl -fS --output-dir /debs/ \
          -LO https://github.com/oneapi-src/level-zero/releases/download/v${LEVEL_ZERO_VERSION}/libze-dev_${LEVEL_ZERO_VERSION}+u24.04_amd64.deb && \
-    if ! sha256sum --check $CHECKSUMS_LOADER $CHECKSUMS_BACKEND ; then \
-	echo "--- Expected ($CHECKSUMS_LOADER / $CHECKSUMS_BACKEND): ---"; \
-	cat $CHECKSUMS_LOADER $CHECKSUMS_BACKEND; \
-	echo "--- Got: ---"; \
-	sha256sum *.deb; \
-	echo "=> ERROR"; \
-	exit 1; \
-    fi; \
+    if ! sha256sum --check --strict $CHECKSUMS_LOADER $CHECKSUMS_BACKEND ; then \
+        echo "--- Expected ($CHECKSUMS_LOADER / $CHECKSUMS_BACKEND): ---"; \
+        cat $CHECKSUMS_LOADER $CHECKSUMS_BACKEND; \
+        echo "--- Got: ---"; \
+        sha256sum *.deb; \
+        echo "=> ERROR"; \
+        exit 1; \
+    fi && \
     dpkg -i /debs/*.deb
 
 # Install IGSC build dependencies
