xpumd/level-zero-go: verify driver stack DEB file checksums
Dev-SHA: e77005c849c061204e826da6976f65998ccfb58f

diff --git a/xpumd/level-zero-go/examples/Dockerfile b/xpumd/level-zero-go/examples/Dockerfile
--- a/xpumd/level-zero-go/examples/Dockerfile
+++ b/xpumd/level-zero-go/examples/Dockerfile
@@ -7,22 +7,26 @@ FROM golang:1.26-trixie AS builder
 
 ARG APP=list-sysman
 
-# DEB package versions
+# driver stack DEB package versions
 ARG IGC_CORE_VERSION=2.34.4+21428
 ARG COMPUTE_RUNTIME_RELEASE=26.18.38308.1
 ARG LIBIGDGMM12_VERSION=22.10.0
 ARG LEVEL_ZERO_VERSION=1.28.6
 
-# Git repo tags & matching commit hashes
+# SHA256 checksums for those
+ARG CHECKSUMS_LOADER=checksums-loader.txt
+ARG CHECKSUMS_BACKEND=checksums-backend.txt
+
+# Git repo tags & commit hashes to match against them
 ARG IGSC_VERSION=V0.9.6
 ARG IGSC_COMMIT=6abae21408bc36561baaade9fca9ae4a5173d2f0
 ARG METEE_VERSION=6.2.3
 ARG METEE_COMMIT=67ff323aead437557d9a7309803aae79cd5b2d56
 
-WORKDIR /go/src/work
+WORKDIR /debs/
+COPY level-zero/$CHECKSUMS_LOADER level-zero/$CHECKSUMS_BACKEND .
 
-RUN mkdir /debs && \
-    IGC_CORE_RELEASE=${IGC_CORE_VERSION%%+*} && \
+RUN IGC_CORE_RELEASE=${IGC_CORE_VERSION%%+*} && \
     curl -fS --fail-early --output-dir /debs/ \
          -LO https://github.com/intel/intel-graphics-compiler/releases/download/v${IGC_CORE_RELEASE}/intel-igc-core-2_${IGC_CORE_VERSION}_amd64.deb \
          -LO https://github.com/intel/compute-runtime/releases/download/${COMPUTE_RUNTIME_RELEASE}/libigdgmm12_${LIBIGDGMM12_VERSION}_amd64.deb \
@@ -34,6 +38,14 @@ RUN mkdir /debs && \
 
 RUN curl -fS --output-dir /debs/ \
          -LO https://github.com/oneapi-src/level-zero/releases/download/v${LEVEL_ZERO_VERSION}/libze-dev_${LEVEL_ZERO_VERSION}+u24.04_amd64.deb && \
+    if ! sha256sum --check $CHECKSUMS_LOADER $CHECKSUMS_BACKEND ; then \
+	echo "--- Expected ($CHECKSUMS_LOADER / $CHECKSUMS_BACKEND): ---"; \
+	cat $CHECKSUMS_LOADER $CHECKSUMS_BACKEND; \
+	echo "--- Got: ---"; \
+	sha256sum *.deb; \
+	echo "=> ERROR"; \
+	exit 1; \
+    fi; \
     dpkg -i /debs/*.deb
 
 # Install IGSC build dependencies
@@ -41,6 +53,8 @@ RUN apt-get update && apt-get install -y --no-install-recommends \
     cmake \
     ninja-build \
     libudev-dev
+
+WORKDIR /go/src/work
 
 # Build IGSC + its MeTee dependency
 # (with --depth 1, clone $TAG + checkout $COMMIT verifies that tags & hashes match)
