xpumd: add go-tidy make target
Runs go mod tidy in every Go module.

Signed-off-by: Markus Lehtonen <markus.lehtonen@intel.com>

Dev-SHA: 58fa1b6e6bec6954ddb67636911d7b0c1ee05c58

diff --git a/xpumd/Makefile b/xpumd/Makefile
--- a/xpumd/Makefile
+++ b/xpumd/Makefile
@@ -186,7 +186,7 @@ check-modfiles:
 	@error=""; for module in $(GO_MODULES); do \
 		echo "Checking module '$$module'"; \
 		if ! (cd $$module && go mod tidy -diff 2> /dev/null); then \
-			echo "ERROR: go.mod file in '$$module' is out of sync. Run 'go mod tidy' in that directory to fix it."; \
+			echo "ERROR: go.mod file in '$$module' is out of sync. Run 'make go-tidy' to fix it."; \
 			error=1; \
 		fi; \
 	done; \
@@ -194,6 +194,13 @@ check-modfiles:
 		exit 1; \
 	fi; \
 	echo "✓ All go.mod files are in sync"
+
+.PHONY: go-tidy
+go-tidy:
+	for module in $(GO_MODULES); do \
+		echo "Running go mod tidy in '$$module'"; \
+		go -C $$module mod tidy || exit 1; \
+	done; \
 
 .PHONY: go-fix
 go-fix:
